### ISSUE TITLE
about running the code

### ISSUE THREAD

**Issue by xuesanshi** [divelab/lgcn#3]
When I try to run the pubmed and citeseer datasets respectively, ValueError: Cannot feed value of shape (354, 3) for Tensor 'labels:0', which has shape '(?, 7)' and the data is out of bounds, etc. I want to ask if your framework fits into these two data sets? Or is there a problem with me?how to solution it? thinks

**Comment by HongyangGao** [comment]
Hi there,

Please change the number of classes in main.py accordingly.
