### ISSUE TITLE
some question about the select adjacent nodes features？

### ISSUE THREAD

**Issue by xuesanshi** [divelab/lgcn#7]
First of all, thank you for answering my question many times，When I read your thesis, I found that you used the maximum pooling features of K nodes when you selected the neighborhood information of a point. But can I consider learning a weighted adjacency matrix first, and get the neighborhood features according to the weight of the center point and the neighboring point?think you

**Comment by HongyangGao** [comment]
> ```
>     First of all, thank you for answering my question many times，When I read your thesis, I found that you used the maximum pooling features of K nodes when you selected the neighborhood information of a point. But can I consider learning a weighted adjacency matrix first, and get the neighborhood features according to the weight of the center point and the neighboring point?think you
> ```

Yes, this is used to select fixed number (k) of nodes for the center node to do convolution. However, this selection is performed in each channel separately. This means it may select different nodes for different channels. Hope this helps.
